---
fixtures:
  repositories:
    datacat:
      repo: 'https://github.com/richardc/puppet-datacat.git'
      ref: '0.5.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.2.0'
  symlinks:
    mcollective: '#{source_dir}'
