---
fixtures:
  repositories:
    datacat:
      repo: 'https://github.com/simp/puppet-datacat.git'
      ref: 'simp-0.6.2'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.9.0'
    java_ks:
      repo: 'https://github.com/simp/puppetlabs-java_ks.git'
      ref: 'simp-1.4.0'
  symlinks:
    mcollective: '#{source_dir}'
